### PR TITLE
clippy'd benches + examples

### PR DESCRIPTION
**Pull request by llogiq**

### CODE REVIEW

**Comment by fitzgen** [comment]
Uh oh, those Travis CI results are rather unhappy.

**Comment by fitzgen** [comment]
Looks like it is some new warning that did not exist before, and we are now triggering via `#![deny(warnings)]`. Maybe we should remove that.

**Comment by llogiq** [comment]
The error seems unrelated, [I have an explanation](https://github.com/llogiq/patterns/blob/f08e132761c379bd466c19c797d0b8d132363cef/anti_patterns/deny-warnings.md)

**Comment by fitzgen** [comment]
Removing deny(warnings) in #171 -- assuming that is green, will merge this right afterwards.

Thanks for your patience!

**Comment by fitzgen** [comment]
CI should pass now with a rebase, would you mind rebasing @llogiq ? If not, I can get to it later today.

**Comment by llogiq** [comment]
I may find the time later today. Otherwise feel free to rebase.

**Comment by fitzgen** [comment]
Rebased and merged in #174 -- thanks @llogiq!

**Pull request closed without merging**
