### PR TITLE
Miscellaneous cleanups

### PR DESCRIPTION
**Pull request by khuey**
While messing around in src/op.rs I cleaned up a couple things.

### CODE REVIEW

**Comment by tromey** [comment]
The first patch is totally fine.

For the second patch, I think the rationale behind a mutable context is that we didn't want to assume a readonly context.  Obviously there's no concrete use for this at this time, but my thought was perhaps some implementation would want to be caching results or something along those lines.

**Comment by khuey** [comment]
The methods on `EvaluationContext` don't take mutable self refs though ...

**Comment by philipc** [comment]
I think it's better to change `callbacks` to be a value, not a reference. Then the caller can choose which type of reference they want.

**Comment by khuey** [comment]
fwiw I don't think the Travis failure is me. Looks like a compiler upgrade broke some existing code?

**Comment by tromey** [comment]
> The methods on EvaluationContext don't take mutable self refs though ...

Yeah.  Probably I was confused somehow, it seems likely.  I don't have any objections to this; and since it seems like we're contemplating changing the API anyway...

**Comment by fitzgen** [comment]
Looks like a change in type inference.

```
---- src/cfi.rs - cfi::CfiEntriesIter (line 551) stdout ----
	error[E0282]: type annotations needed
  --> <anon>:25:1
   |
25 | Ok(())
   | ^^ cannot infer type for `E`
```

**Comment by khuey** [comment]
Something like that, perhaps?

**Comment by khuey** [comment]
I'm going to end up rewriting everything in this PR for #184, so let's not bother what this.

**Pull request closed without merging**
