### PR TITLE
Add some text to expression evaluator documentation

### PR DESCRIPTION
**Pull request by tromey**

### CODE REVIEW

**Comment by jonhoo** [comment]
While we're updating this, I'd like to also see a somewhat longer description for `set_max_iterations`. In particular, it is unclear what exactly "iterations" means. Also, the use of `None` in the description doesn't match the interface (which takes a `u32`, not an `Option<u32>`).

**Comment by tromey** [comment]
Thanks for the suggestions!  I'll fix up this patch tomorrow.

**Comment by tromey** [comment]
For the `None` thing, what is going on is that the API is asymmetric -- you can set the max iterations but you can't clear it.  This capability didn't seem very important so I left it out.

**Comment by jonhoo** [comment]
@tromey I think that's fine (not letting the user clear it), but I think it is then not right for the method documentation to talk about `None`.

**Comment by jonhoo** [comment]
LGTM, r+

**Pull request merged**
