### PR TITLE
Link to the DWARF standard in the README

### PR DESCRIPTION
**Pull request by fitzgen**
Care to rubber stamp this, @philipc ?

### CODE REVIEW

**Comment by jonhoo** [comment]
Should this also have a link to DWARFv4 given that that's what we really support atm?

**Comment by fitzgen** [comment]
We should in theory support DWARF 2 through 4 since they are mostly backwards compatible and we attempt to handle the differences between each version. 5 is also mostly backwards compatible as well, we just don't understand the semantics of new attributes and tags.

So, I don't know if it is worth pointing to a specific version when we're aiming for support of all modern versions of DWARF... Do you think it is that big of a deal?

**Comment by jonhoo** [comment]
Eh, no, you're probably right. Never mind. LGTM, r+

**Comment by fitzgen** [comment]
Going to just merge now, since Linux is green and OSX is backlogged, and this is just a README change anyways.

**Pull request merged**
