### PR TITLE
Fix dwarfdump stdout handling

### PR DESCRIPTION
**Pull request by rocallahan**
See commit message. This more than doubles dwarfdump output speed on my optimized build of Firefox `libxul.so`.

### CODE REVIEW

**Comment by fitzgen** [comment]
Is the speed up mostly from locking stdout or from increasing buffering from every newline to some larger buffer size?

@philipc do you think it is even worth investing in speed ups for our example dwarfdump?

**Comment by rocallahan** [comment]
> Is the speed up mostly from locking stdout or from increasing buffering from every newline to some larger buffer size?

The latter, I believe. The cost of a syscall should greatly exceed the cost of acquiring and releasing an uncontended lock unless something has gone very wrong.

> do you think it is even worth investing in speed ups for our example dwarfdump?

When studying the debuginfo for libxul or other large binaries, dwarfdump performance really matters to me. The large size of the output (libxul.so generates 24G of output) means it's impractical to just dump to a file once and repeatedly search that file. I have some additional patches to speed it up using parallelism and filtering.

gimli's dwarfdump may only be an "example" but it's very useful in its own right. objdump/readelf don't support newer DWARF5 stuff and are not especially fast --- with these patches, gimli dwarfdump is slightly faster, and the pending changes I have make gimli dwarfdump much faster. libdwarf's dwarfdump is nasty. I'd rather hack on gimli's dwarfdump than the others since we're using gimli internally, and Rust vs C --- I'd hate to implement the parallelism stuff in C.

If you don't want to take these patches, that's fine; I'll fork dwarfdump for our own use.

**Comment by fitzgen** [comment]
That's a pretty convincing argument!

**Comment by philipc** [comment]
This is fine. Note that stdout does use `LineWriter`, so this results in double buffering. I don't think there's any way to avoid that currently though, and the inner buffer will mostly be bypassed since it has a smaller capacity.

Is it worth giving dwarfdump its own crate (while keeping it in this repo)?

**Pull request merged**
