### PR TITLE
Use EndianBuf throughout Evaluation.

### PR DESCRIPTION
**Pull request by khuey**
Not really sure why this isn't this way to begin with.

### CODE REVIEW

**Comment by tromey** [comment]
> Not really sure why this isn't this way to begin with.

I thought the whole gimli API just asked users to pass in an `&[u8]` and that `EndianBuf` was generally only used internally.  E.g., `DebugInfo::new` does this.

I don't mind this change but I think it shouldn't be made to just one part of the API.

**Comment by khuey** [comment]
`DebugInfo::new` input comes from a raw ELF section.  In practice, `Evaluation::new` input comes from an `AttributeValue::ExprLoc` or a `LocationListEntry::data` both of which are `EndianBuf`s.

**Comment by tromey** [comment]
I'd rather @fitzgen decide.

**Comment by fitzgen** [comment]
The elf sections take raw input, yes, because that's how you enter our API. Everything after that should be tracking its endianity in the types.

**Pull request merged**
